### ISSUE TITLE
multiple errors in json file on website

### ISSUE THREAD

**Issue by MasterHaze1986** [BurgosManuel/dzsalauncher-updater#1]
Hi, let me start by thanking you for the help correcting this issue with the dzsa launcher.

Just wanted to let you know that there are multiple errors in the file generated on your page to fix the "There was a problem downloading server list one or more errors occurred" error.

In multiple spots the time code is listed with one digit too many for minutes. ("time": "01:069", instead of     "time": "01:06",)
The other error is that in various spots it lists DayzCN instead of the time stamp. ( "time": "DayzCN" instead of  "time": "01:06")

Also, not so much a error but more of a "ease of use" issue, the file generated is all on a single line making finding errors a bit more tedious.

Once the errors are corrected manually, the file works perfectly and corrects the original error. :)

[dayz-servers (generated by website).json](https://github.com/BurgosManuel/dzsalauncher-updater/files/13086369/dayz-servers.generated.by.website.json)
[dayz-servers (manually corrected).json](https://github.com/BurgosManuel/dzsalauncher-updater/files/13086383/dayz-servers.manually.corrected.json)

**Comment by BurgosManuel** [comment]
Hi MasterHaze! 👋 Thank you so much for taking the time to review this project and helping me to improve it. I made a new update based on the cases you describe, the new changes are:

- Times with minutes with more than 3 digits will be reduce to 2 -> "01:069" will now be **"01:06".**
- Times with TEXT instead of an actual time will be removed from the server list (this is a particular case with the **DayzCN** servers).
- **The JSON output will be formatted**, so it will be easier to read and find new possible errors in the future :D!
- I added **new logs to the web console**, so you can verify wich servers had their times updated and wich ones were removed.

Again, thank you so much for your help, and i will be glad to fix any other errors you might find! 💪❤
